### ISSUE TITLE
Call of Duty 4: Modern Warfare support

### ISSUE THREAD

**Issue by ghost** [marvinl97/CoD-SCZ-FoV-Changer#2]
MW1 is absent for some reason, the game doesn't use VAC according to the store page: http://store.steampowered.com/app/7940/?snr=1_7_7_151_150_1

**Comment by marvinlehmann** [comment]
I thought that you can easily change the field of view using `cg_fov XX` in the console or config. But I'm wrong. Apparently it works with keybinds. I'll see what I can do. =)

Just leaving this link here: http://pcgamingwiki.com/wiki/Call_of_Duty_4:_Modern_Warfare#Field_of_view_.28FOV.29

**Comment by marvinlehmann** [comment]
I was wrong, you can change the fov in the console. I just forgot to activate the console in the options >.>
I think cg_fovScale is broken in the singleplayer. cg_fov works fine.

So you can bind the fov command or just write it into the console. I think there isn't the need for a fov changer because of the console.

**Comment by ghost** [comment]
@marvinl97 Do console commands stick? If I set FOV once, does it reset after map load or game restart? If it does your tool would still be useful.

**Comment by marvinlehmann** [comment]
The fov is apparently saved at checkpoints. But you could: /bind w "+forward;cg_fov XX".
Didn't test it myself though.
Does cg_fovScale work for you? And what's your CoD SP version? 
Mine is version 1.5 (CoD4 1.5 build 549 Thu Oct 04 2007) as retail.

---

```
FovPointer = new Memory.Pointer((IntPtr)0x007F77CC, new short[] {0xC}),
FovScalePointer = new Memory.Pointer((IntPtr)0x????????, new short[] {0xC}) // isn't included??
```

**Comment by ghost** [comment]
I don't currently have the game installed. I will at some point test your tool with all supported games and report if there are any issues.

**Comment by marvinlehmann** [comment]
Okay!

**Comment by 07416** [comment]
@1.7 is the latest version: https://pcgamingwiki.com/wiki/Call_of_Duty_4:_Modern_Warfare#Patches
Binding FOV command to a key is possible: https://pcgamingwiki.com/wiki/Call_of_Duty_4:_Modern_Warfare#Field_of_view_.28FOV.29

I see no harm in adding support for the game, using your tool is a far easier method for an average player.

**Comment by ghost** [comment]
@marvinlehmann [1.7](https://pcgamingwiki.com/wiki/Call_of_Duty_4:_Modern_Warfare#Patches) is the latest version and [binding FOV command to a key](https://pcgamingwiki.com/wiki/Call_of_Duty_4:_Modern_Warfare#Field_of_view_.28FOV.29) is possible.

I see no harm in adding support for the game, using your tool is a far easier method for an average player.
