### ISSUE TITLE
Add support for Modern Warfare Remastered

### ISSUE THREAD

**Issue by Keith94** [marvinl97/CoD-SCZ-FoV-Changer#4]
The game has just been released, and it seems the single-player campaign at least is lacking an FOV option.

Is there any chance of adding support for it in the future?

EDIT: New fix released here: https://community.pcgamingwiki.com/files/file/950-modern-warfare-remastered-singleplayer-fov-fix/

**Comment by marvinlehmann** [comment]
I would love to support it but I don't have access to it to get the memory adresses. Furthermore I won't buy it bundled with IW for such an outrageous price. Maybe there are some people that could send pull requests or addresses to me.

Do IW and MWR not have any anti cheat at the moment?

EDIT: I think I would have to change a few things for x64 support.

**Comment by Keith94** [comment]
> Do IW and MWR not have any anti cheat at the moment?

There doesn't appear to be any confirmation yet about having anti cheat in either games...

Still it shouldn't affect single-player/zombies modes either way, right?

**Comment by marvinlehmann** [comment]
Yeah, it's unlikey but I think it was BO2 zombies that had anti cheat enabled? I'm not sure.

**Comment by ElGreeko** [comment]
Hi. Love your work on CoD SCZ! Could finally play MW2's SP again because of you! <3


I saw that you "would love to support it [MWR] but I don't have access to it to get the memory adresses".

Is there a way to give these addresses to you, or help you in one way or another (I myself have the game and would love to have an FOV changer for the SP)?

**Comment by Keith94** [comment]
If you know the default FOV value, it may be possible using "float scan" in Cheat Engine to find the addresses, or something similar like that.

For example: [Change FOV Obscuritas Cheat engine - YouTube](https://www.youtube.com/watch?v=ty1qh8oRu_w)

**Comment by marvinlehmann** [comment]
@ElGreeko Game files (.exe, .dlls) would be enough for experienced people but not for me. :/ I'm a noob in "reverse engineering". Furthermore I never debugged/"hacked" a 64bit game. So I'm not even sure if I could get it work. I'm also quite busy right now (university..). Sorry.

But yeah, you could try to use Cheat Engine as @Keith94 suggested it.

**Comment by Keith94** [comment]
Good news: a single-player FOV fix was just released 😄
https://community.pcgamingwiki.com/files/file/950-modern-warfare-remastered-singleplayer-fov-fix/
