### ISSUE TITLE
Could you give build details?

### ISSUE THREAD

**Issue by Guacamole-1** [marvinl97/CoD-SCZ-FoV-Changer#8]
could you say how you built from source please? I really like this project and would like to make this work for my modded cod

**Comment by marvinlehmann** [comment]
I always used Visual Studio to build it. But you can also build it directly with MSBuild:
https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild?view=vs-2022
But most likely some tool versions have to be updated in the sln/csproj. =)

**Comment by Guacamole-1** [comment]
i tried but it gave some errors what version did you use?

**Comment by marvinlehmann** [comment]
`<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>` in csproj and MSBuild 17.0.0.52104 =)

**Comment by Guacamole-1** [comment]
i installed .net 6 and this error apears when i do dotnet build:

`C:\Program Files (x86)\dotnet\sdk\6.0.102\Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\mcdnv\Desktop\CoD-SCZ-FoV-Changer\CoD SCZ FoV Changer\CoD SCZ FoV Changer.csproj]`

i installed developer packs for version 4.8 but cant find version 6

**Comment by Guacamole-1** [comment]
and when i try the old version i get this:

`"C:\Users\mcdnv\Desktop\CoD-SCZ-FoV-Changer\CoD SCZ FoV Changer\CoD SCZ FoV Changer.csproj" (default target) (1) ->
(CoreCompile target) ->
  CallOfDuty.cs(20,20): error CS1056: Unexpected character '$' [C:\Users\mcdnv\Desktop\CoD-SCZ-FoV-Changer\CoD SCZ FoV
Changer\CoD SCZ FoV Changer.csproj]
  FrmMain.cs(155,57): error CS1056: Unexpected character '$' [C:\Users\mcdnv\Desktop\CoD-SCZ-FoV-Changer\CoD SCZ FoV Ch
anger\CoD SCZ FoV Changer.csproj]`

**Comment by marvinlehmann** [comment]
Try installing the build tools with this installer https://aka.ms/vs/17/release/vs_buildtools.exe and also select ".NET Framework 4.8 targeting pack" in the individual components tab. =)

And don't forget to change 4.5 to 4.8:

> `<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>` in CoD SCZ FoV Changer.csproj

**Comment by Guacamole-1** [comment]
i dont have visual studio only vs code

**Comment by Guacamole-1** [comment]
i am using vs code not visual studio, i prefer doing things in a console

**Comment by Guacamole-1** [comment]
do you have a link without it being vs? i am using visual studio code and i already installed https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48 both dev pack and runtime
i prefer using the terminal and vs takes up a lot of space

**Comment by marvinlehmann** [comment]
The name is a bit misleading (I guess?) but this doesn't install the visual studio.

**Comment by Guacamole-1** [comment]
oh, ok i installed it and it worked thank you so much :)

**Comment by marvinlehmann** [comment]
That's nice! No problem =)
